/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "PerfectMatching.h"
/* Header for class oarlib_graph_util_BlossomV */

#ifndef _Included_oarlib_graph_util_BlossomV
#define _Included_oarlib_graph_util_BlossomV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oarlib_graph_util_BlossomV
 * Method:    blossomV
 * Signature: (II[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_oarlib_graph_util_BlossomV_blossomV
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
