/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oarlib_graph_util_MSArbor */

#ifndef _Included_oarlib_graph_util_MSArbor
#define _Included_oarlib_graph_util_MSArbor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oarlib_graph_util_MSArbor
 * Method:    msArbor
 * Signature: (II[I)[I
 */
JNIEXPORT jintArray JNICALL Java_oarlib_graph_util_MSArbor_msArbor
  (JNIEnv *, jclass, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
